repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run pytest tests
        entry: pytest
        language: system
        types: [python]
        always_run: true
        pass_filenames: false